SENSITIVE_CLASSES = {
    "Passwords",
    "Email addresses",
    "Phone numbers",
    "Physical addresses",
    "Credit cards",
    "Government issued IDs",
    "Social security numbers",
    "Bank account numbers",
}


def calculate_threat(breaches, lookup=None, free_risk=None):
    score = free_risk.get("score", 0) if free_risk else 0

    if lookup and lookup.get("status") == "ok":
        for breach in breaches:
            score += 12
            data_classes = set(breach.get("DataClasses") or [])
            score += min(len(data_classes) * 2, 12)
            score += 12 if data_classes & SENSITIVE_CLASSES else 0
            score += 8 if breach.get("IsSensitive") else 0
            score += 4 if breach.get("IsVerified") else 0

    return min(score, 100)


def get_risk_label(score):
    if score >= 75:
        return "CRITICAL"
    if score >= 50:
        return "HIGH"
    if score >= 25:
        return "MEDIUM"
    if score > 0:
        return "LOW"
    return "LOW"


def get_recommendations(score, lookup=None):
    recommendations = [
        "Use unique passwords generated by a password manager.",
        "Enable multi-factor authentication on email, banking, and social accounts.",
        "Review account recovery emails and phone numbers for your key accounts.",
    ]

    if lookup and lookup.get("status") != "ok":
        recommendations.insert(0, "This score uses free risk signals because HIBP breach lookup is not configured.")
        recommendations.append("Optional: add HIBP_API_KEY for confirmed breach matches.")
        recommendations.append("Optional: add a free EMAILREP_API_KEY for richer reputation checks.")

    if score >= 50:
        recommendations.insert(0, "Treat this address as higher risk and review its account security immediately.")
        recommendations.append("Watch for phishing attempts that reference old public data.")
    elif score >= 25:
        recommendations.insert(0, "Review the warning signals and strengthen login protection.")
    else:
        recommendations.insert(0, "No major free risk signals were detected, but keep monitoring periodically.")

    return recommendations
